### ISSUE TITLE
Create Landing Page Component

### ISSUE THREAD

**Issue by Yasholma** [BuildForSDG/SmeVest-Frontend#4]
**Is your feature request related to a problem? Please describe.**
Create a landing page for unauthenticated users.

**Describe the solution you'd like**
A landing page should have a login and register button to enable guests to create account.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by achingachris** [comment]
the landing page isn't that responsive on some devices

**Comment by Yasholma** [comment]
> the landing page isn't that responsive on some devices

What section?

**Comment by achingachris** [comment]
the view

> > the landing page isn't that responsive on some devices
> 
> What section?

the VW on the landing page only

**Comment by Yasholma** [comment]
Header? Home Section or the Footer? because I previewed it on different viewports while developing

**Comment by Yasholma** [comment]
Issue has been solved.
